In [ ]:
import pandas as pd

In [ ]:
datos_alquiler = pd.read_csv('/content/drive/MyDrive/dataframe data/alquiler', sep = ';')

In [ ]:
datos_alquiler.shape

(32960, 9)

In [ ]:
datos_alquiler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tipo           32960 non-null  object
 1   Distrito       32960 non-null  object
 2   Cuartos        32960 non-null  int64
 3   Vacantes       32960 non-null  int64
 4   Suites         32960 non-null  int64
 5   Area           32960 non-null  int64
 6   Valor          32943 non-null  float64
 7   Mantenimiento  28867 non-null  float64
 8   Impuesto       22723 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.3+ MB

In [ ]:
datos_alquiler.head(50)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,Local comercial,Ate,0,4,0,150,5200.0,4020.0,1111.0
3,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
4,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
5,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
6,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
7,Casa en condominio,Ate,5,4,5,750,22000.0,NaN,NaN
8,Casa en condominio,El Agustino,2,2,0,65,1000.0,NaN,NaN
9,Local comercial,Pachacámac,0,3,0,695,35000.0,19193.0,3030.0
10,Departamento,Pachacámac,1,0,0,36,1200.0,NaN,NaN
11,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0
12,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0
13,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0
14,Habitación,San Borja,1,0,0,27,1800.0,501.0,NaN
15,Departamento,San Borja,4,3,1,243,13000.0,2000.0,803.0
16,Edificio completo,Chorrillos,0,0,0,536,28000.0,NaN,3563.0
17,Flat,Chorrillos,3,1,1,80,3800.0,1040.0,NaN
18,Casa en condominio,San Luis,3,1,1,115,2000.0,NaN,NaN
19,Departamento,Callao,3,0,0,54,950.0,300.0,28.0
20,Departamento,Ate,2,1,1,67,1700.0,589.0,147.0
21,Departamento,San Miguel,2,1,0,110,1900.0,700.0,138.0
22,Casa en condominio,Ate,4,3,2,466,7500.0,2695.0,NaN
23,Departamento,Santa Rosa,3,1,0,68,1000.0,670.0,NaN
24,Departamento,San Miguel,2,1,0,78,2000.0,700.0,NaN
25,Flat,Rímac,1,0,0,56,4500.0,1900.0,1500.0
26,Local comercial,Punta Negra,0,1,0,25,1100.0,600.0,NaN
27,Departamento,Comas,3,1,1,125,7000.0,2100.0,463.0
28,Departamento,San Miguel,1,0,0,48,750.0,772.0,25.0
29,Tienda/Salón,Lince,0,1,0,35,1300.0,950.0,NaN
30,Departamento,Ate,3,3,1,175,4200.0,1500.0,500.0
31,Casa,Lince,4,1,2,400,12000.0,NaN,NaN
32,Departamento,Chorrillos,2,1,0,76,2500.0,740.0,NaN
33,Departamento,San Borja,3,1,2,378,10000.0,2150.0,700.0
34,Departamento,San Borja,3,0,0,180,5500.0,1780.0,420.0
35,Local comercial,Ate,0,1,0,22,700.0,NaN,NaN
36,Departamento,Jesús María,3,1,1,105,2300.0,648.0,NaN
37,Departamento,Rímac,3,1,0,110,3900.0,1500.0,120.0
38,Local comercial,Pachacámac,0,5,0,1306,117540.0,19486.0,NaN
39,Habitación,San Borja,1,0,0,27,1300.0,380.0,53.0
40,Departamento,Miraflores,3,3,1,200,3500.0,1780.0,496.0
41,Departamento,Ate,3,1,2,70,1800.0,1095.0,140.0
42,Local comercial,Jesús María,0,1,0,50,1500.0,250.0,NaN
43,Departamento,San Borja,4,1,0,244,5000.0,2500.0,4100.0
44,Departamento,Ate,3,2,1,110,4500.0,2000.0,450.0
45,Local comercial,Pachacámac,0,0,0,460,7500.0,4797.0,2019.0
46,Local comercial,Pachacámac,0,0,0,1170,140456.0,23409.0,5852.0
47,Departamento,Jesús María,2,2,2,90,3000.0,1340.0,NaN
48,Departamento,Jesús María,3,2,2,100,2600.0,380.0,NaN
49,Departamento,Ate,3,1,1,72,2350.0,600.0,70.0

In [ ]:
list(datos_alquiler['Tipo'].drop_duplicates())

['Habitación',
 'Casa',
 'Local comercial',
 'Departamento',
 'Casa en condominio',
 'Edificio completo',
 'Flat',
 'Tienda/Salón',
 'Almacén',
 'Casa comercial',
 'Casa de villa',
 'Terreno',
 'Cochera',
 'Loft',
 'Tienda en Centro Comercial',
 'Chacra',
 'Terreno em condominio',
 'Oficina',
 'Chalet',
 'Studio',
 'Hotel',
 'Local industrial']

In [ ]:
viviendas =  ['Habitación',
 'Casa',
 'Departamento',
 'Casa en condominio',
 'Flat',
 'Casa comercial',
 'Casa de villa',
 'Cochera',
 'Loft'
]

In [ ]:
filtro_vivienda =datos_alquiler['Tipo'].isin(viviendas)

In [ ]:
filtro_vivienda

0         True
1         True
2        False
3         True
4         True
         ...
32955     True
32956     True
32957     True
32958     True
32959    False
Name: Tipo, Length: 32960, dtype: bool

In [ ]:
datos_viviendas = datos_alquiler[filtro_vivienda]

In [ ]:
datos_viviendas

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
3,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
4,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
5,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
32954,Cochera,Pachacámac,0,0,0,755,14000.0,NaN,NaN
32955,Habitación,Pachacámac,0,0,0,27,800.0,350.0,25.0
32956,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0
32957,Departamento,Rímac,2,1,0,48,1400.0,509.0,37.0
32958,Departamento,Rímac,2,0,0,70,3000.0,760.0,NaN

In [ ]:
datos_viviendas.shape

(23454, 9)

In [ ]:
datos_viviendas.index = range(datos_viviendas.shape[0])

In [ ]:
datos_viviendas.head(50)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
4,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
5,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
6,Casa en condominio,Ate,5,4,5,750,22000.0,NaN,NaN
7,Casa en condominio,El Agustino,2,2,0,65,1000.0,NaN,NaN
8,Departamento,Pachacámac,1,0,0,36,1200.0,NaN,NaN
9,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0
10,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0
11,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0
12,Habitación,San Borja,1,0,0,27,1800.0,501.0,NaN
13,Departamento,San Borja,4,3,1,243,13000.0,2000.0,803.0
14,Flat,Chorrillos,3,1,1,80,3800.0,1040.0,NaN
15,Casa en condominio,San Luis,3,1,1,115,2000.0,NaN,NaN
16,Departamento,Callao,3,0,0,54,950.0,300.0,28.0
17,Departamento,Ate,2,1,1,67,1700.0,589.0,147.0
18,Departamento,San Miguel,2,1,0,110,1900.0,700.0,138.0
19,Casa en condominio,Ate,4,3,2,466,7500.0,2695.0,NaN
20,Departamento,Santa Rosa,3,1,0,68,1000.0,670.0,NaN
21,Departamento,San Miguel,2,1,0,78,2000.0,700.0,NaN
22,Flat,Rímac,1,0,0,56,4500.0,1900.0,1500.0
23,Departamento,Comas,3,1,1,125,7000.0,2100.0,463.0
24,Departamento,San Miguel,1,0,0,48,750.0,772.0,25.0
25,Departamento,Ate,3,3,1,175,4200.0,1500.0,500.0
26,Casa,Lince,4,1,2,400,12000.0,NaN,NaN
27,Departamento,Chorrillos,2,1,0,76,2500.0,740.0,NaN
28,Departamento,San Borja,3,1,2,378,10000.0,2150.0,700.0
29,Departamento,San Borja,3,0,0,180,5500.0,1780.0,420.0
30,Departamento,Jesús María,3,1,1,105,2300.0,648.0,NaN
31,Departamento,Rímac,3,1,0,110,3900.0,1500.0,120.0
32,Habitación,San Borja,1,0,0,27,1300.0,380.0,53.0
33,Departamento,Miraflores,3,3,1,200,3500.0,1780.0,496.0
34,Departamento,Ate,3,1,2,70,1800.0,1095.0,140.0
35,Departamento,San Borja,4,1,0,244,5000.0,2500.0,4100.0
36,Departamento,Ate,3,2,1,110,4500.0,2000.0,450.0
37,Departamento,Jesús María,2,2,2,90,3000.0,1340.0,NaN
38,Departamento,Jesús María,3,2,2,100,2600.0,380.0,NaN
39,Departamento,Ate,3,1,1,72,2350.0,600.0,70.0
40,Departamento,Breña,2,2,1,180,4000.0,2500.0,300.0
41,Departamento,Jesús María,3,1,2,92,2300.0,840.0,200.0
42,Departamento,Pachacámac,1,0,0,27,750.0,371.0,19.0
43,Departamento,Comas,1,0,0,35,2000.0,650.0,75.0
44,Departamento,Comas,1,0,0,38,1400.0,530.0,77.0
45,Departamento,Jesús María,2,1,2,83,1600.0,1160.0,157.0
46,Casa en condominio,Ate,5,10,5,1600,25000.0,1600.0,NaN
47,Departamento,Ate,4,3,3,153,6500.0,2300.0,434.0
48,Departamento,Ancón,4,3,4,267,18000.0,3100.0,400.0
49,Departamento,Comas,3,1,0,87,3200.0,1305.0,217.0

In [ ]:
datos_viviendas.to_csv('alquileres_viviendas.csv',sep=';')

In [ ]:
list(datos_alquiler['Tipo'].drop_duplicates())

['Habitación',
 'Casa',
 'Local comercial',
 'Departamento',
 'Casa en condominio',
 'Edificio completo',
 'Flat',
 'Tienda/Salón',
 'Almacén',
 'Casa comercial',
 'Casa de villa',
 'Terreno',
 'Cochera',
 'Loft',
 'Tienda en Centro Comercial',
 'Chacra',
 'Terreno em condominio',
 'Oficina',
 'Chalet',
 'Studio',
 'Hotel',
 'Local industrial']

In [ ]:
locales_comerciales =[
 'Local comercial',
 'Tienda/Salón',
 'Almacén',
 'Casa comercial',
 'Cochera',
 'Tienda en Centro Comercial',
 'Local industrial']

In [ ]:
filtro_locales_comerciales =datos_alquiler['Tipo'].isin(locales_comerciales)

In [ ]:
dalos_locales_comerciales = datos_alquiler[filtro_locales_comerciales]

In [ ]:
dalos_locales_comerciales.shape

(9459, 9)

In [ ]:
dalos_locales_comerciales

In [ ]:
dalos_locales_comerciales.index = range(dalos_locales_comerciales.shape[0])

In [ ]:
dalos_locales_comerciales.head(50)

In [ ]:
dalos_locales_comerciales.to_csv('locales_comerciales.csv',sep=';')